# aws cloudformation delete-stack --stack-name scikit-image
# aws cloudformation create-stack --stack-name scikit-image --template-body file://build-image.yml

Description: Create a CodePipeline for creating a Docker base image for training/serving models
Parameters:
  RepoBranchName:
    Type: String
    Description: Name of the branch the code is located
  ImageRepoName:
    Type: String
    Description: Name of the ECR repo without the image name
  ImageTagName:
    Type: String
    Description: Name of the ECR image tag
    Default: latest

Resources:
  BuildImageProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub mlops-buildimage-${AWS::StackName}
      Description: Build a Model Image
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/MLOpsCodeBuild
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        EnvironmentVariables:
          - Name: IMAGE_REPO_NAME
            Value:
              Ref: ImageRepoName
          - Name: IMAGE_TAG
            Value:
              Ref: ImageTagName
          - Name: AWS_ACCOUNT_ID
            Value: !Sub ${AWS::AccountId}
          - Name: AWS_DEFAULT_REGION
            Value: !Sub ${AWS::Region}
          - Name: TEMPLATE_BUCKET
            Value: !Sub mlops-${AWS::Region}-${AWS::AccountId}
          - Name: TEMPLATE_PREFIX
            Value: codebuild
      Tags:
        - Key: Name
          Value: !Sub mlops-buildimage-${AWS::StackName}

  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub mlops-${AWS::StackName}
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/MLOps
      ArtifactStore:
          Type: S3
          Location: !Sub mlops-${AWS::Region}-${AWS::AccountId}
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: GetSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                -
                  Name: ModelSourceOutput
              Configuration:
                BranchName: 
                  Ref: RepoBranchName
                RepositoryName: mlops
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: BuildImage
              InputArtifacts:
                - Name: ModelSourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                  ProjectName:
                    Ref: BuildImageProject
              RunOrder: 1
  
