# aws cloudformation delete-stack --stack-name iris-model-dev
# aws cloudformation create-stack --stack-name iris-model-dev --template-body file://deploy-model-dev.yml --parameters file://deploy-model-dev.json

Description: Deploy a model at Sagemaker
Parameters:
  ImageRepoName:
    Type: String
    Description: Name of the model image ECR (Docker) repo
  ImageTagName:
    Type: String
    Description: Name of the model image ECR (Docker) tag
  ModelName:
    Type: String
    Description: Name of the model
  TrainJobId:
    Type: String
    Description: Id of the Codepipeline + SagemakerJobs
    
Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub mlops-${ModelName}-${TrainJobId}
      PrimaryContainer:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepoName}:${ImageTagName}
        ModelDataUrl: !Sub s3://sagemaker-${AWS::Region}-${AWS::AccountId}/${ModelName}/mlops-${ModelName}-${TrainJobId}/output/model.tar.gz
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/MLOps
  
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
      - InitialInstanceCount: 1
        InitialVariantWeight: 1.0
        InstanceType: ml.t2.large
        ModelName: !GetAtt Model.ModelName
        VariantName: !GetAtt Model.ModelName
          
      EndpointConfigName: !Sub mlops-ec-${ModelName}-dev-${TrainJobId}
      Tags:
        - Key: Name
          Value: !Sub mlops-ec-${ModelName}-dev-${TrainJobId}
    DependsOn: Model

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub mlops-${ModelName}-dev-${TrainJobId}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      Tags:
        - Key: Name
          Value: !Sub mlops-${ModelName}-dev-${TrainJobId}
    DependsOn: EndpointConfig

  

  